config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # user operation
  get "users/whoami"
  post "users/login"
  delete "users/logout"
  post "users/register"

  # lobby operation
  get "lobby/join/:id", to: 'lobby#join'
  get "lobby/exit"
  get "lobby/ready"
  get "lobby/unready"
  get "lobby/check_allready"

  # game operation
  get "game/is_in_game"
  get "game/turn_state"
  get "game/end_turn"
  get "game/draw_card"
  get "game/exit_room"

  # card operation
  post "card/use"
  post "card/buy"

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id           :integer          not null, primary key
#  status       :string
#  name         :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  turn_counter :integer
#

class Room < ApplicationRecord
  has_many :users
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end


  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.status = "waiting"
    respond_to do |format|
      if(!@current_user.room_id.nil?)
        format.html { render :new }
        format.json { render json: {status: 'fail', message: 'need to exit room before creating a new one'} }
      else
        if @room.save
          @current_user.room_id = @room.id
          @current_user.status = 'unready'
          @current_user.save
          format.html { redirect_to @room, notice: 'Room was successfully created.' }
          format.json { render :show, status: :ok, location: @room }
        else
          format.html { render :new }
          format.json { render json: @room.errors, status: 'fail' }
        end
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:status, :name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %>
    <%= f.text_field :status %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.status %></td>
        <td><%= room.name %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @room.status %>
</p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>